config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'products#index'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<head>
  <%= stylesheet_link_tag 'style' %>
</head>

<body>
  <header class="header">
    <section class="container">
      <nav class="nav">
        <figure class="logo">
          <img src="<%= asset_path('logo.png') %>">
        </figure>
        <input type="checkbox" id="nav-toggle" class="nav-toggle">
        <label for="nav-toggle" class="nav-toggle-lable">
          <img src="<%= asset_path('menuMobileimage.png') %>">
        </label>
        <ul class="menu">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Shop by Catergory', root_path %></li>
          <li><%= link_to 'My List', root_path %></li>
          <li><%= link_to 'Sign Up', sign_up_path %></li>
          <li><%= link_to 'Log In', sign_in_path %></li>
        </ul>
      </nav>
    </section>
  </header>

  <h1>Online Grocery</h1>
  <% if Current.user %>
    Logged in as: <%= Current.user.email %><br>
    <%= link_to 'Edit Password', edit_password_path %>
    <%= button_to 'Logout', logout_path, method: :delete %>
  <% else %>
  <%= link_to 'Sign Up', sign_up_path %>
  or
  <%= link_to 'Login', sign_in_path %>
  <% end %>
</body>